user: seed
passwd: password123
email: your@email.com
domain: testcloudbox.ml
transmission:
  user: seed
  passwd: password321
  downloads: "/home/{{user}}/downloads/transmission"
nzbget:
  downloads: "/home/{{user}}/downloads/nzbget"
rutorrent:
  downloads: "/home/{{user}}/downloads/rutorrent"
