---
- debug:
    msg: "System is running {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: Verify system is Ubuntu 16.04
  fail: msg="This playbook is specifically designed for Ubuntu 16.04. Please dont bother removing this sanity check as I dont want to be mass closing non issues because people have decided to bypass this check. If you do, your on your own."
  when: ansible_distribution_version | version_compare('16.04', '!=')

- name: Verify a tag was provided
  fail: msg="You must supply a tag via the --tags option
  when: tags is not defined