---
- name: Stop and remove any existing container
  docker_container:
    name: radarr
    state: absent

- name: Create and start container
  docker_container:
    name: radarr
    image: hotio/radarr
    published_ports:
      - "127.0.0.1:7878:7878"
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
      VERSION: latest
      MONO_TLS_PROVIDER: legacy
      VIRTUAL_HOST: "radarr.{{domain}}"
      VIRTUAL_PORT: 7878
      LETSENCRYPT_HOST: "radarr.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/radarr:/config"
      - "/mnt/unionfs/Media/Movies:/movies"
      - "{{nzbget.downloads}}:/downloads/nzbget"
      - "{{rutorrent.downloads}}:/downloads/rutorrent"
      - "{{transmission.downloads}}:/downloads/transmission"
      - "/opt/scripts:/scripts"
    networks:
      - name: cloudbox
        ipv4_address: 172.18.0.14
        aliases:
          - radarr
    restart_policy: always
    state: started
