---
- name: Stop and remove any existing container
  docker_container:
    name: sonarr
    state: absent

- name: Create and start container
  docker_container:
    name: sonarr
    image: "linuxserver/sonarr:develop"
    published_ports:
      - "127.0.0.1:8989:8989"
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
      MONO_TLS_PROVIDER: legacy
      VIRTUAL_HOST: "sonarr.{{domain}}"
      VIRTUAL_PORT: 8989
      LETSENCRYPT_HOST: "sonarr.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/sonarr:/config"
      - "/mnt/unionfs/Media/TV:/tv"
      - "{{nzbget.downloads}}:/downloads/nzbget"
      - "{{rutorrent.downloads}}:/downloads/rutorrent"
      - "{{transmission.downloads}}:/downloads/transmission"
    networks:
      - name: cloudbox
        ipv4_address: 172.18.0.13
        aliases:
          - sonarr
    restart_policy: always
    state: started
